INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('1', 'T1', 'Passenger, Mail & Ca', 75, 150, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('2', 'T2', 'Passenger, Mail & Ca', 100, 90, 41);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('3', 'T3', 'Express Passenger wi', 175, 330, 94);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('4', 'T4', 'Passenger, Mail & Ca', 150, 220, 29);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('5', 'T5', 'Passenger & Cargo', 200, 180, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('6', 'T6', 'Passenger with Dinin', 175, 80, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('7', 'T7', 'Passenger & Cargo', 75, 250, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('8', 'T8', 'Passenger & Cargo', 150, 220, 59);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('9', 'T9', 'Passenger & Cargo', 75, 320, 171);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('10', 'T10', 'Passenger with Dinin', 75, 320, 43);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('11', 'T11', 'Passenger', 100, 120, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('12', 'T12', 'Passenger & Mail', 50, 120, 84);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('13', 'T13', 'Passenger & Cargo', 50, 320, 192);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('14', 'T14', 'Passenger, Mail & Ca', 50, 150, 135);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('15', 'T15', 'Passenger with Dinin', 175, 300, 26);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('16', 'T16', 'Passenger with Dinin', 150, 180, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('17', 'T17', 'Passenger & Mail', 125, 120, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('18', 'T18', 'Passenger & Cargo', 150, 220, 73);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('19', 'T19', 'Passenger & Cargo', 150, 320, 85);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('20', 'T20', 'Passenger', 125, 150, 54);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('21', 'T21', 'Passenger', 200, 80, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('22', 'T22', 'Passenger', 175, 180, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('23', 'T23', 'Passenger', 100, 180, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('24', 'T24', 'Express Passenger & ', 150, 330, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('25', 'T25', 'Passenger, Mail & Ca', 100, 120, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('26', 'T26', 'Passenger, Mail & Ca', 125, 180, 29);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('27', 'T27', 'Express Passenger, M', 200, 330, 58);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('28', 'T28', 'Passenger & Mail', 200, 320, 72);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('29', 'T29', 'Passenger with Dinin', 100, 320, 16);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('30', 'T30', 'Passenger & Cargo', 75, 250, 117);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('31', 'T31', 'Express Passenger wi', 175, 330, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('32', 'T32', 'Passenger', 200, 250, 31);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('33', 'T33', 'Passenger', 100, 120, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('34', 'T34', 'Passenger, Mail & Ca', 75, 90, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('35', 'T35', 'Passenger & Mail', 175, 150, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('36', 'T36', 'Passenger', 75, 220, 15);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('37', 'T37', 'Passenger & Mail', 150, 250, 67);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('38', 'T38', 'Passenger & Mail', 175, 320, 91);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('39', 'T39', 'Passenger, Mail & Ca', 125, 220, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('40', 'T40', 'Express Passenger & ', 200, 330, 83);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('41', 'T41', 'Passenger', 150, 220, 29);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('42', 'T42', 'Passenger with Dinin', 200, 120, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('43', 'T43', 'Passenger & Mail', 150, 150, 35);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('44', 'T44', 'Passenger & Mail', 150, 120, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('45', 'T45', 'Passenger', 125, 80, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('46', 'T46', 'Passenger', 125, 80, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('47', 'T47', 'Passenger', 100, 320, 16);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('48', 'T48', 'Passenger', 125, 120, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('49', 'T49', 'Passenger, Mail & Ca', 200, 250, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('50', 'T50', 'Express Passenger & ', 150, 330, 22);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('51', 'T51', 'Passenger, Mail & Ca', 150, 150, 2);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('52', 'T52', 'Express Passenger & ', 150, 330, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('53', 'T53', 'Passenger, Mail & Ca', 75, 320, 107);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('54', 'T54', 'Passenger', 100, 80, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('55', 'T55', 'Passenger, Mail & Ca', 125, 120, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('56', 'T56', 'Passenger', 75, 320, 107);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('57', 'T57', 'Passenger, Mail & Ca', 125, 220, 53);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('58', 'T58', 'Passenger', 100, 220, 99);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('59', 'T59', 'Passenger & Cargo', 50, 180, 72);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('60', 'T60', 'Passenger & Mail', 50, 150, 105);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('61', 'T61', 'Passenger & Mail', 75, 320, 149);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('62', 'T62', 'Passenger, Mail & Ca', 125, 220, 53);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('63', 'T63', 'Passenger & Cargo', 50, 250, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('64', 'T64', 'Passenger', 150, 250, 67);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('65', 'T65', 'Passenger & Mail', 75, 80, 21);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('66', 'T66', 'Passenger', 125, 120, 1);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('67', 'T67', 'Passenger & Mail', 75, 80, 43);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('68', 'T68', 'Passenger & Mail', 175, 300, 26);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('69', 'T69', 'Passenger, Mail & Ca', 175, 120, 7);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('70', 'T70', 'Passenger with Dinin', 200, 180, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('71', 'T71', 'Passenger & Mail', 200, 250, 63);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('72', 'T72', 'Passenger', 200, 180, 23);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('73', 'T73', 'Passenger', 150, 320, 21);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('74', 'T74', 'Passenger, Mail & Ca', 100, 80, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('75', 'T75', 'Passenger & Mail', 125, 150, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('76', 'T76', 'Passenger', 75, 90, 42);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('77', 'T77', 'Passenger, Mail & Ca', 100, 250, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('78', 'T78', 'Passenger & Mail', 175, 320, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('79', 'T79', 'Passenger with Dinin', 50, 90, 81);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('80', 'T80', 'Express Passenger wi', 50, 330, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('81', 'T81', 'Passenger & Mail', 125, 150, 42);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('82', 'T82', 'Passenger & Mail', 175, 300, 43);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('83', 'T83', 'Passenger with Dinin', 75, 120, 56);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('84', 'T84', 'Passenger with Dinin', 100, 90, 23);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('85', 'T85', 'Passenger, Mail & Ca', 50, 320, 64);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('86', 'T86', 'Express Passenger wi', 175, 330, 38);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('87', 'T87', 'Passenger & Cargo', 200, 150, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('88', 'T88', 'Passenger, Mail & Ca', 150, 300, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('89', 'T89', 'Passenger, Mail & Ca', 150, 250, 25);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('90', 'T90', 'Passenger & Mail', 100, 120, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('91', 'T91', 'Passenger & Mail', 125, 250, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('92', 'T92', 'Passenger & Cargo', 125, 150, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('93', 'T93', 'Passenger', 200, 90, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('94', 'T94', 'Passenger & Mail', 50, 300, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('95', 'T95', 'Passenger & Cargo', 75, 150, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('96', 'T96', 'Luxary Passenger & C', 50, 250, 25);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('97', 'T97', 'Passenger & Mail', 150, 180, 42);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('98', 'T98', 'Express Passenger wi', 150, 330, 77);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('99', 'T99', 'Passenger & Mail', 50, 150, 105);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('100', 'T100', 'Passenger & Cargo', 50, 320, 192);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('101', 'T101', 'Passenger & Mail', 125, 180, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('102', 'T102', 'Passenger & Mail', 50, 150, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('103', 'T103', 'Express Passenger', 50, 330, 99);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('104', 'T104', 'Passenger & Cargo', 50, 220, 44);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('105', 'T105', 'Passenger with Dinin', 150, 150, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('106', 'T106', 'Passenger with Dinin', 200, 180, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('107', 'T107', 'Passenger with Dinin', 175, 180, 31);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('108', 'T108', 'Passenger, Mail & Ca', 75, 220, 117);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('109', 'T109', 'Passenger & Cargo', 125, 180, 43);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('110', 'T110', 'Passenger, Mail & Ca', 125, 120, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('111', 'T111', 'Passenger & Cargo', 200, 120, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('112', 'T112', 'Passenger with Dinin', 150, 250, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('113', 'T113', 'Express Passenger & ', 100, 330, 149);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('114', 'T114', 'Passenger, Mail & Ca', 75, 300, 2);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('115', 'T115', 'Passenger', 125, 180, 65);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('116', 'T116', 'Express Passenger, M', 200, 330, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('117', 'T117', 'Express Passenger', 75, 330, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('118', 'T118', 'Passenger & Mail', 75, 80, 53);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('119', 'T119', 'Passenger & Mail', 50, 180, 144);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('120', 'T120', 'Passenger & Mail', 75, 220, 59);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('121', 'T121', 'Express Passenger wi', 50, 330, 99);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('122', 'T122', 'Express Passenger', 125, 330, 26);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('123', 'T123', 'Passenger & Mail', 200, 320, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('124', 'T124', 'Passenger with Dinin', 125, 300, 108);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('125', 'T125', 'Passenger with Dinin', 75, 90, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('126', 'T126', 'Passenger with Dinin', 150, 220, 51);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('127', 'T127', 'Passenger & Mail', 150, 320, 43);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('128', 'T128', 'Passenger, Mail & Ca', 150, 220, 73);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('129', 'T129', 'Passenger & Mail', 100, 80, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('130', 'T130', 'Passenger', 175, 180, 51);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('131', 'T131', 'Passenger with Dinin', 150, 90, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('132', 'T132', 'Passenger with Dinin', 125, 320, 115);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('133', 'T133', 'Express Passenger', 150, 330, 99);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('134', 'T134', 'Passenger', 100, 80, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('135', 'T135', 'Passenger with Dinin', 200, 300, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('136', 'T136', 'Passenger & Cargo', 125, 250, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('137', 'T137', 'Express Passenger & ', 150, 330, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('138', 'T138', 'Passenger with Dinin', 150, 250, 58);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('139', 'T139', 'Passenger, Mail & Ca', 125, 90, 22);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('140', 'T140', 'Passenger & Cargo', 125, 300, 72);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('141', 'T141', 'Passenger & Cargo', 50, 80, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('142', 'T142', 'Passenger, Mail & Ca', 175, 220, 31);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('143', 'T143', 'Luxary Passenger', 50, 250, 25);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('144', 'T144', 'Passenger & Mail', 50, 120, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('145', 'T145', 'Passenger & Mail', 100, 120, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('146', 'T146', 'Passenger with Dinin', 125, 220, 53);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('147', 'T147', 'Passenger & Mail', 125, 220, 35);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('148', 'T148', 'Passenger & Mail', 200, 250, 63);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('149', 'T149', 'Passenger & Cargo', 200, 80, 8);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('150', 'T150', 'Passenger, Mail & Ca', 175, 220, 63);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('151', 'T151', 'Passenger, Mail & Ca', 200, 320, 48);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('152', 'T152', 'Passenger, Mail & Ca', 125, 320, 13);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('153', 'T153', 'Passenger, Mail & Ca', 175, 320, 91);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('154', 'T154', 'Passenger', 150, 150, 15);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('155', 'T155', 'Passenger', 75, 150, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('156', 'T156', 'Passenger, Mail & Ca', 200, 220, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('157', 'T157', 'Passenger & Cargo', 200, 90, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('158', 'T158', 'Express Passenger & ', 200, 330, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('159', 'T159', 'Passenger with Dinin', 200, 300, 53);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('160', 'T160', 'Passenger', 50, 80, 64);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('161', 'T161', 'Passenger, Mail & Ca', 150, 80, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('162', 'T162', 'Passenger & Mail', 175, 150, 21);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('163', 'T163', 'Luxary Passenger wit', 50, 300, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('164', 'T164', 'Passenger & Cargo', 125, 180, 22);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('165', 'T165', 'Passenger & Cargo', 50, 180, 126);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('166', 'T166', 'Passenger & Cargo', 175, 250, 64);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('167', 'T167', 'Passenger & Cargo', 150, 90, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('168', 'T168', 'Passenger & Cargo', 150, 180, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('169', 'T169', 'Express Passenger, M', 175, 330, 47);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('170', 'T170', 'Passenger', 50, 180, 144);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('171', 'T171', 'Passenger with Dinin', 75, 80, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('172', 'T172', 'Passenger & Cargo', 100, 220, 66);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('173', 'T173', 'Passenger & Cargo', 100, 90, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('174', 'T174', 'Passenger & Mail', 175, 90, 23);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('175', 'T175', 'Passenger', 200, 90, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('176', 'T176', 'Passenger', 100, 320, 96);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('177', 'T177', 'Passenger', 200, 80, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('178', 'T178', 'Passenger, Mail & Ca', 50, 80, 8);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('179', 'T179', 'Express Passenger & ', 175, 330, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('180', 'T180', 'Passenger & Mail', 125, 180, 58);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('181', 'T181', 'Passenger & Mail', 100, 320, 128);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('182', 'T182', 'Passenger & Cargo', 200, 250, 25);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('183', 'T183', 'Express Passenger wi', 175, 330, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('184', 'T184', 'Passenger & Mail', 150, 150, 1);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('185', 'T185', 'Passenger', 75, 320, 21);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('186', 'T186', 'Passenger & Cargo', 175, 220, 38);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('187', 'T187', 'Passenger', 125, 320, 64);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('188', 'T188', 'Passenger & Mail', 200, 320, 8);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('189', 'T189', 'Passenger & Mail', 100, 150, 68);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('190', 'T190', 'Passenger & Cargo', 75, 150, 1);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('191', 'T191', 'Passenger with Dinin', 125, 80, 13);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('192', 'T192', 'Passenger, Mail & Ca', 175, 220, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('193', 'T193', 'Passenger, Mail & Ca', 175, 300, 69);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('194', 'T194', 'Passenger, Mail & Ca', 100, 180, 54);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('195', 'T195', 'Passenger with Dinin', 50, 120, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('196', 'T196', 'Passenger, Mail & Ca', 125, 80, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('197', 'T197', 'Passenger & Cargo', 100, 90, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('198', 'T198', 'Passenger & Cargo', 50, 320, 96);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('199', 'T199', 'Passenger, Mail & Ca', 100, 220, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('200', 'T200', 'Passenger & Cargo', 100, 300, 45);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('201', 'T201', 'Passenger, Mail & Ca', 50, 80, 72);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('202', 'T202', 'Passenger & Mail', 75, 320, 128);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('203', 'T203', 'Passenger with Dinin', 50, 90, 27);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('204', 'T204', 'Passenger with Dinin', 100, 220, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('205', 'T205', 'Express Passenger, M', 75, 330, 154);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('206', 'T206', 'Express Passenger & ', 125, 330, 132);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('207', 'T207', 'Passenger & Mail', 200, 180, 32);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('208', 'T208', 'Passenger', 75, 320, 171);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('209', 'T209', 'Passenger & Mail', 150, 220, 44);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('210', 'T210', 'Passenger, Mail & Ca', 125, 300, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('211', 'T211', 'Passenger', 125, 320, 38);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('212', 'T212', 'Passenger', 150, 150, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('213', 'T213', 'Passenger, Mail & Ca', 200, 320, 64);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('214', 'T214', 'Passenger & Cargo', 150, 150, 25);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('215', 'T215', 'Passenger, Mail & Ca', 75, 90, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('216', 'T216', 'Passenger, Mail & Ca', 75, 90, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('217', 'T217', 'Passenger with Dinin', 75, 300, 2);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('218', 'T218', 'Passenger, Mail & Ca', 125, 300, 108);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('219', 'T219', 'Passenger', 75, 180, 96);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('220', 'T220', 'Passenger, Mail & Ca', 75, 180, 96);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('221', 'T221', 'Passenger & Mail', 125, 80, 26);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('222', 'T222', 'Passenger', 100, 150, 23);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('223', 'T223', 'Passenger & Cargo', 200, 320, 56);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('224', 'T224', 'Express Passenger & ', 75, 330, 198);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('225', 'T225', 'Passenger with Dinin', 175, 150, 13);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('226', 'T226', 'Passenger', 175, 300, 51);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('227', 'T227', 'Passenger, Mail & Ca', 75, 250, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('228', 'T228', 'Express Passenger & ', 150, 330, 44);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('229', 'T229', 'Passenger', 100, 80, 8);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('230', 'T230', 'Passenger, Mail & Ca', 150, 320, 85);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('231', 'T231', 'Passenger & Cargo', 100, 80, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('232', 'T232', 'Passenger & Mail', 175, 220, 44);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('233', 'T233', 'Passenger & Mail', 150, 90, 15);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('234', 'T234', 'Passenger & Cargo', 50, 320, 16);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('235', 'T235', 'Passenger', 150, 250, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('236', 'T236', 'Passenger & Mail', 75, 180, 84);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('237', 'T237', 'Passenger', 125, 180, 65);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('238', 'T238', 'Passenger with Dinin', 75, 180, 108);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('239', 'T239', 'Passenger with Dinin', 175, 220, 44);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('240', 'T240', 'Express Passenger, M', 175, 330, 85);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('241', 'T241', 'Passenger with Dinin', 175, 250, 71);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('242', 'T242', 'Passenger & Mail', 150, 150, 1);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('243', 'T243', 'Passenger with Dinin', 100, 180, 54);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('244', 'T244', 'Passenger & Cargo', 175, 300, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('245', 'T245', 'Passenger', 150, 180, 54);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('246', 'T246', 'Passenger, Mail & Ca', 125, 220, 88);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('247', 'T247', 'Passenger', 75, 220, 44);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('248', 'T248', 'Passenger & Mail', 200, 120, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('249', 'T249', 'Passenger', 75, 250, 83);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('250', 'T250', 'Passenger with Dinin', 175, 80, 23);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('251', 'T251', 'Passenger with Dinin', 175, 250, 57);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('252', 'T252', 'Passenger, Mail & Ca', 200, 80, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('253', 'T253', 'Express Passenger', 175, 330, 38);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('254', 'T254', 'Passenger & Mail', 100, 150, 68);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('255', 'T255', 'Passenger', 50, 300, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('256', 'T256', 'Passenger & Mail', 75, 80, 53);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('257', 'T257', 'Passenger & Mail', 175, 90, 13);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('258', 'T258', 'Passenger with Dinin', 150, 180, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('259', 'T259', 'Passenger with Dinin', 200, 220, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('260', 'T260', 'Passenger, Mail & Ca', 200, 300, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('261', 'T261', 'Express Passenger & ', 200, 330, 66);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('262', 'T262', 'Passenger, Mail & Ca', 75, 150, 1);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('263', 'T263', 'Passenger with Dinin', 50, 90, 45);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('264', 'T264', 'Passenger & Mail', 50, 150, 105);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('265', 'T265', 'Express Passenger', 175, 330, 94);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('266', 'T266', 'Passenger, Mail & Ca', 200, 80, 2);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('267', 'T267', 'Passenger & Mail', 50, 220, 88);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('268', 'T268', 'Passenger & Mail', 175, 80, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('269', 'T269', 'Passenger & Mail', 175, 90, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('270', 'T270', 'Passenger & Cargo', 125, 90, 32);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('271', 'T271', 'Passenger & Cargo', 50, 320, 32);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('272', 'T272', 'Passenger', 75, 180, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('273', 'T273', 'Passenger & Cargo', 200, 250, 31);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('274', 'T274', 'Passenger & Mail', 100, 250, 25);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('275', 'T275', 'Passenger & Mail', 75, 80, 27);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('276', 'T276', 'Express Passenger', 175, 330, 47);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('277', 'T277', 'Passenger & Mail', 150, 120, 16);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('278', 'T278', 'Passenger, Mail & Ca', 200, 120, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('279', 'T279', 'Passenger, Mail & Ca', 175, 120, 1);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('280', 'T280', 'Passenger with Dinin', 75, 150, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('281', 'T281', 'Passenger, Mail & Ca', 50, 90, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('282', 'T282', 'Express Passenger, M', 150, 330, 88);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('283', 'T283', 'Express Luxary Passe', 50, 330, 297);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('284', 'T284', 'Passenger', 75, 150, 7);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('285', 'T285', 'Passenger', 200, 300, 38);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('286', 'T286', 'Express Passenger', 125, 330, 119);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('287', 'T287', 'Passenger & Cargo', 100, 250, 113);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('288', 'T288', 'Passenger', 175, 120, 27);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('289', 'T289', 'Passenger', 175, 300, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('290', 'T290', 'Passenger, Mail & Ca', 175, 180, 21);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('291', 'T291', 'Passenger', 75, 300, 12);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('292', 'T292', 'Passenger with Dinin', 200, 320, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('293', 'T293', 'Passenger, Mail & Ca', 50, 90, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('294', 'T294', 'Passenger & Mail', 150, 120, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('295', 'T295', 'Passenger', 125, 220, 79);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('296', 'T296', 'Express Passenger, M', 175, 330, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('297', 'T297', 'Passenger with Dinin', 200, 320, 48);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('298', 'T298', 'Passenger & Cargo', 100, 300, 15);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('299', 'T299', 'Passenger with Dinin', 50, 250, 175);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('300', 'T300', 'Passenger & Cargo', 175, 150, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('301', 'T301', 'Passenger', 200, 80, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('302', 'T302', 'Passenger with Dinin', 50, 80, 48);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('303', 'T303', 'Express Passenger & ', 150, 330, 33);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('304', 'T304', 'Passenger', 175, 300, 77);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('305', 'T305', 'Passenger with Dinin', 150, 90, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('306', 'T306', 'Passenger', 150, 90, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('307', 'T307', 'Passenger with Dinin', 100, 250, 13);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('308', 'T308', 'Passenger & Mail', 175, 320, 46);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('309', 'T309', 'Passenger with Dinin', 200, 150, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('310', 'T310', 'Passenger, Mail & Ca', 100, 300, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('311', 'T311', 'Passenger & Cargo', 175, 220, 63);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('312', 'T312', 'Passenger with Dinin', 100, 150, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('313', 'T313', 'Passenger & Mail', 150, 150, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('314', 'T314', 'Passenger, Mail & Ca', 150, 80, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('315', 'T315', 'Passenger', 150, 120, 8);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('316', 'T316', 'Passenger & Cargo', 125, 150, 3);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('317', 'T317', 'Passenger & Mail', 125, 300, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('318', 'T318', 'Passenger & Mail', 125, 90, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('319', 'T319', 'Passenger', 150, 220, 66);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('320', 'T320', 'Passenger, Mail & Ca', 150, 150, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('321', 'T321', 'Passenger, Mail & Ca', 175, 300, 34);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('322', 'T322', 'Passenger & Cargo', 150, 120, 4);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('323', 'T323', 'Passenger, Mail & Ca', 200, 220, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('324', 'T324', 'Passenger, Mail & Ca', 50, 150, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('325', 'T325', 'Passenger', 200, 180, 23);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('326', 'T326', 'Passenger & Cargo', 50, 150, 75);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('327', 'T327', 'Passenger & Cargo', 200, 150, 19);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('328', 'T328', 'Passenger & Mail', 175, 120, 14);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('329', 'T329', 'Express Passenger', 150, 330, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('330', 'T330', 'Passenger & Mail', 75, 150, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('331', 'T331', 'Passenger, Mail & Ca', 100, 320, 64);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('332', 'T332', 'Passenger with Dinin', 50, 90, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('333', 'T333', 'Passenger & Mail', 50, 80, 24);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('334', 'T334', 'Passenger with Dinin', 100, 220, 11);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('335', 'T335', 'Passenger with Dinin', 175, 90, 13);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('336', 'T336', 'Passenger & Mail', 50, 90, 9);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('337', 'T337', 'Passenger', 100, 90, 18);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('338', 'T338', 'Passenger & Cargo', 100, 120, 6);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('339', 'T339', 'Passenger with Dinin', 200, 220, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('340', 'T340', 'Express Passenger & ', 125, 330, 132);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('341', 'T341', 'Passenger with Dinin', 75, 300, 2);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('342', 'T342', 'Express Passenger', 200, 330, 17);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('343', 'T343', 'Passenger & Cargo', 100, 80, 36);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('344', 'T344', 'Passenger, Mail & Ca', 100, 180, 27);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('345', 'T345', 'Passenger & Mail', 150, 120, 28);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('346', 'T346', 'Passenger', 175, 250, 29);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('347', 'T347', 'Passenger & Mail', 175, 120, 27);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('348', 'T348', 'Express Passenger & ', 200, 330, 5);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('349', 'T349', 'Passenger & Mail', 150, 300, 7);
INSERT INTO public.trains (train_id, train_name, train_descript, seats_num, top_speed, price_mile) VALUES ('350', 'T350', 'Express Passenger', 150, 330, 11);